language: php

php:
  - 7.1

before_script:
  - composer install --no-interaction --no-scripts

env:
  - APP_KEY=base64:oKkca01Gaxi9n+4iJlF6VL1QIHp49Ln6VTa6N61O4Ws= AMO_USE_MIGRATION=no APP_ENV=local

script:
  
